In [42]:
def is_even(n):
    return n&1==0

if(is_even(54)):
    print("even")
else:
    print("odd")

even


In [43]:
def greet(name="Guest"):
    print(f"Hello {name}. Welcome to the Paradise.")

greet()
greet("chris")

Hello Guest. Welcome to the Paradise.
Hello chris. Welcome to the Paradise.


In [44]:
# def func(*args):
#     return max(args)
  
# print(func(1, 2, 3, 4, 5))

# def funcx(*args):
#     s=0
#     for i in args:
#         s+=i
#     return s
# print(funcx(10, 20, 30, 40, 50))

 
# def funcy(**kwargs):
#     for key, value in kwargs.items():
#         print(f"{key} = {value}")
# funcy(name="chris", age=30, city="New York")


def fun(*args, **kwargs):
    print(max(args))
    for k,v in kwargs.items():
        print(f"{k}: {v}")


fun(1, 2, 3, 4, 5, name="chris", age=30)



5
name: chris
age: 30


In [45]:
def add(x, y):
    return x + y,x,y

print(add(10, 20))

print(type(add(10, 20)))

(30, 10, 20)
<class 'tuple'>


In [46]:
add= lambda args:sum(args)
add((1,2,3,4,5))

15

In [47]:
sqr_list=list(map(lambda x:  x**2 if x % 2 == 0 else x, range(1,11)))

print(sqr_list)

[1, 4, 3, 16, 5, 36, 7, 64, 9, 100]


In [48]:
l1=[1, 2, 3, 4, 5]
l2=[6, 7, 8, 9, 10]

print(list(map(lambda x,y:x+y,l1,l2)))

num=['1', '2', '3', '4', '5']
print(list(map(int, num)))

[7, 9, 11, 13, 15]
[1, 2, 3, 4, 5]


In [49]:
lst =[1, 2, 3, 4, 5]

print(list(filter(lambda x:x&1==0 and x>0,lst)))  

[2, 4]


In [50]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
import importlib
import pkg.lol as lol
from pkg.subpkg import hello

importlib.reload(lol)
importlib.reload(hello)

hello.callHello()

lol.Call()



Calling hello from subpkg!!
Calling LOL from pkg!!


In [ ]:
with open("temp.txt","w") as f:
    f.write("Hello World!\n")
    f.write("This is a test file.\n")                               

In [3]:
lines=['first line\n', 'second line\n', 'third line\n']
with open("temp.txt","a") as f:
    f.writelines(lines)

In [13]:
try:
    # a=b
    # b=10/0
    # with open("teemp.txt", "r") as f:
    #     content = f.read()
    #     print(content)
    a = 10
except NameError as e:
    print(f"NameError: {e}")
except ZeroDivisionError as e:
    print(f"ZeroDivisionError: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
else:
    print("No exceptions occurred and variables are set correctly. a =",a  )
finally:
    print("This block always executes, regardless of exceptions.")

No exceptions occurred and variables are set correctly. a = 10
This block always executes, regardless of exceptions.


In [16]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def display_info(self):
        print(f"Car Make: {self.make}, Model: {self.model}, Year: {self.year}")

bmw = Car("BMW", "X5", 2020)
bmw.display_info()

Car Make: BMW, Model: X5, Year: 2020


In [ ]:
class dog:
    def __init__(self,breed="Not given",name="Not given"):
        self.breed = breed
        self.name = name
    
    def display_info(self):
        print(f"Dog Breed: {self.breed}, Name: {self.name}")    

dog1 = dog("Labrador", "Buddy")
dog1.display_info()
print("Dog Breed:", dog1.breed)
print("Dog Name:", dog1.name)

dog2 = dog()
dog2.display_info()
        



Dog Breed: Labrador, Name: Buddy
Dog Breed: Labrador
Dog Name: Buddy
Dog Breed: Not given, Name: Not given


Current balance: 0
Deposited: 500. New balance: 500
Withdrew: 200. New balance: 300
Current balance: 300
Account Number: 123456789, Owner: John Doe, Balance: 300
Cannot withdraw. 400  As curr balance: 300  Insufficient funds or invalid amount

Creating another account...

Current balance: 1000
Deposited: 300. New balance: 1300
Withdrew: 150. New balance: 1150
Current balance: 1150
Account Number: 987654321, Owner: Jane Smith, Balance: 1150
